### ISSUE TITLE
¿How I could fix the error Models must be owned by only a single documen.... 

### ISSUE THREAD

**Issue by akitxu** [PatrikHlobil/Pandas-Bokeh#88] opened 2020-11-16 21:22 UTC
In the script to pratics that You can still specify a column of the DataFrame as the bar category via the x argument if you do not wish to use the index, I get the error
`RuntimeError: Models must be owned by only a single document, HelpTool(id='6110', ...) is already in a doc
`
¿How I could fix this error?. I will appreciate your help.

**Comment by PatrikHlobil** [comment] 2020-11-19 15:04
Hi @akitxu , 

could you please provide a minimal example to reproduce the error?

Best Patrik

**Comment by PatrikHlobil** [comment] 2021-03-01 08:55
Duplicate of #90

**Comment by akitxu** [comment] 2021-03-01 18:07
Dear
Given the difficulties in understanding how to customize graphics with bokeh (legends, scales, etc.), and some error like the one that caused this query, I left bokeh aside a bit and focused on knowing other graphic possibilities, without ruling out returning to this in the future (especially if I find a tutorial on the internet). For these reasons, I forgot this query and did not answer it, since I lost the reference script. I apologize. I beg you to remove it from the issues. Kind regards

**Closed** 2021-03-02 16:47 UTC
Labels: duplicate
