### ISSUE TITLE
Issue with Map Plot

### ISSUE THREAD

**Issue by joeborrello** [PatrikHlobil/Pandas-Bokeh#6] opened 2019-01-04 20:55 UTC
When I try to run the Mapplot example, I get the following error when I try to use `plot_bokeh.map`:

>AttributeError: 'function' object has no attribute 'map'

The whole code is as follows:
```python
import pandas as pd
import pandas_bokeh
pandas_bokeh.output_notebook()

df_mapplot = pd.read_csv(r"https://raw.githubusercontent.com/PatrikHlobil/Pandas-Bokeh/master/Documentation/Testdata/populated%20places/populated_places.csv")

df_mapplot["size"] = df_mapplot["pop_max"] / 1000000
df_mapplot.plot_bokeh.map(
    x="longitude",
    y="latitude",
    hovertool_string="""<h2> @{name} </h2> 
    
                        <h3> Population: @{pop_max} </h3>""",
    tile_provider="STAMEN_TERRAIN_RETINA",
    size="size", 
    figsize=(900, 600),
    title="World cities with more than 1.000.000 inhabitants")
```

**Comment by PatrikHlobil** [comment] 2019-01-05 08:48
You have to use version 0.1 for the map plots. You can check the version with
```python 
import pandas_bokeh
print(pandas_bokeh.__version__)
```

You can then upgrade via pip:

    pip install --upgrade pandas-bokeh

If it works, please close the issue. Otherwise, please provide me the error message such that I can check the problem.

**Comment by joeborrello** [comment] 2019-01-07 16:10
Okay, that worked. The originally installed version was 0.0.2, so the pip upgrade fixed that issue. However, I'm not getting the following error:

>ValueError: All values of the <y>-columns have to be restricted to (-90, 90). The <y> value corresponds to the longitude in WGS84 projection.

Which doesn't seem to make sense because the data set itself has values that are both above and below 90 and -90, respectively.

**Comment by PatrikHlobil** [comment] 2019-01-07 21:20
Thas is weird, I cannot reproduce your problem. I used the code you pasted above (works both with output_notebook and output_file):
```python
import pandas as pd
import pandas_bokeh
pandas_bokeh.output_file("mapplot.html")

df_mapplot = pd.read_csv(r"https://raw.githubusercontent.com/PatrikHlobil/Pandas-Bokeh/master/Documentation/Testdata/populated%20places/populated_places.csv")

df_mapplot["size"] = df_mapplot["pop_max"] / 1000000
df_mapplot.plot_bokeh.map(
    x="longitude",
    y="latitude",
    hovertool_string="""<h2> @{name} </h2> 
    
                        <h3> Population: @{pop_max} </h3>""",
    tile_provider="STAMEN_TERRAIN_RETINA",
    size="size", 
    figsize=(900, 600),
    title="World cities with more than 1.000.000 inhabitants")
```

that creates the plot below on my computer:
[mapplot.zip](https://github.com/PatrikHlobil/Pandas-Bokeh/files/2734306/mapplot.zip)

The error message comes from restriction of the latitude (this is actually an error in the ValueError-message since it is not the longitude restriction) of the WGS84 coordinates. The data however does not contain values that exceed this boundaries:


```python
df_mapplot.describe()
```

<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>pop_max</th>      <th>latitude</th>      <th>longitude</th>      <th>size</th>    </tr>  </thead>  <tbody>    <tr>      <th>count</th>      <td>5.000000e+02</td>      <td>500.000000</td>      <td>500.000000</td>      <td>500.000000</td>    </tr>    <tr>      <th>mean</th>      <td>2.786597e+06</td>      <td>25.000442</td>      <td>37.206103</td>      <td>2.786597</td>    </tr>    <tr>      <th>std</th>      <td>3.108616e+06</td>      <td>21.067590</td>      <td>77.569481</td>      <td>3.108616</td>    </tr>    <tr>      <th>min</th>      <td>1.002000e+06</td>      <td>-37.818085</td>      <td>-123.123590</td>      <td>1.002000</td>    </tr>    <tr>      <th>25%</th>      <td>1.283250e+06</td>      <td>17.247772</td>      <td>-7.031884</td>      <td>1.283250</td>    </tr>    <tr>      <th>50%</th>      <td>1.720500e+06</td>      <td>30.661972</td>      <td>46.535048</td>      <td>1.720500</td>    </tr>    <tr>      <th>75%</th>      <td>2.920250e+06</td>      <td>38.591966</td>      <td>110.388075</td>      <td>2.920250</td>    </tr>    <tr>      <th>max</th>      <td>3.567600e+07</td>      <td>60.177509</td>      <td>174.763027</td>      <td>35.676000</td>    </tr>  </tbody></table>

which created the plot. Can you check your DataFrame with the describe() method?

**Comment by joeborrello** [comment] 2019-01-08 19:09
Okay, so one set of apt updates, and upgrades later, the example code works properly. But I'm still getting that error with a data set of my own. Here's what happens when I use `describe()` on that data frame:
_ | Latitude | Longitude
count | 663784.000000 | 663784.000000
mean | 40.765353 | -73.921533
std | 0.089083 | 0.050768
min | 40.499440 | -74.250642
25% | 40.680547 | -73.953867
50% | 40.786001 | -73.924239
75% | 40.845376 | -73.889728
max | 40.911587 | -73.701025

**Comment by PatrikHlobil** [comment] 2019-01-08 19:46
Could you provide me your dataframe (e.g. as pickle or as parquet)? Then I could try it on my computer and figure out what the problem is. Otherwise, I would propose that you try:
`df_mapplot.head(100).plot_bokeh.map(...)`

and if that works you can try to increase the number of rows that you use for the plot to figure out when the problem occurs.

**Comment by joeborrello** [comment] 2019-01-08 20:03
Okay, so using head(100) worked, so maybe there's just too many rows in the data set? It is fairly large data from NYC. I'm including the dataframe also: https://we.tl/t-FBr853It7n

**Comment by PatrikHlobil** [comment] 2019-01-09 16:14
Ok, I found the problem. Your x and y columns contain NaN values. Therefore, checking the min/max values gives NaN and this violates the conditions for latitude and longitude. One should implement a warning that one cannot plot NaN values.

The solution for you would be to filter out the rows with NaN values in Latitude or Longitude:
```python
df_mapplot = df_mapplot[df_mapplot["Latitude"].notnull()&df_mapplot["Longitude"].notnull()]
```

and then to plot the data. Note however that you shouldn't use output_notebook, but output_file. On my computer the notebook crashed because the output was to big. Also, 600.000 points will probably crash your browser, even when using WebGL which is the default for Pandas Bokeh.

**Comment by joeborrello** [comment] 2019-01-09 16:41
Thanks for helping with that - I thought I had gotten rid of all of the NaN values, but I guess not. And thanks for the heads up about notebook versus file output.

**Comment by PatrikHlobil** [comment] 2019-01-09 21:32
You’re welcome. Maybe have a look at the **Output and Layouts** section of the README.md. This could also be interesting for you...

**Comment by Rendiere** [comment] 2019-05-07 11:09
Hey @PatrikHlobil, I'm running into a potentially related issue on the map plot example. 

Using the exact code as in the github readme, I get the error:
```
AttributeError: 'FramePlotMethods' object has no attribute '_data'
```

Version:
```
print(pandas_bokeh.__version__)
> 0.1.1
```

**Comment by PatrikHlobil** [comment] 2019-05-07 14:00
Hi @Rendiere ,

thanks for the bug report. This happens when you don't catch up with all your tests :(. 

Thisis a new bug and is different from the one desribed above. I already fixed it and it will be available with the next release.

If you don't want to wait, just upgrade on the dev version via:

    pip install git+https://github.com/PatrikHlobil/Pandas-Bokeh.git

Best,

Patrik

**Comment by boustrephon** [comment] 2020-04-05 06:38
Hi @PatrikHlobil : I am on 0.3 (from conda on a Mac) and I have the same problem as @Rendiere (AttributeError: 'FramePlotMethods' object has no attribute '_data'). I am using the same code as above.

Python version 3.7.7 (default, Mar 23 2020, 17:31:31) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Pandas version 0.23.4
Bokeh version 2.0.1
Pandas-bokeh version 0.3

**Comment by PatrikHlobil** [comment] 2020-04-05 06:54
Hi @boustrephon,

The cones package is out of date at the moment because there are problems with a dependency relation in used packages. Please install the latest version via pip and report If the issue I solved.

Best Patrik

**Comment by PatrikHlobil** [comment] 2020-05-09 10:45
Hi @boustrephon, @joeborrello,

I just fixed the conda build problem and you can now also install the most recent version of pandas-bokeh (0.4.3) via conda via:

`conda install -c patrikhlobil pandas-bokeh`

Best Patrik

**Closed by PatrikHlobil** 2020-05-09 10:45 UTC
Labels: bug
