### ISSUE TITLE
Using figsize causes "Javascript Error: invalid bbox"

### ISSUE THREAD

**Issue by timhughes** [PatrikHlobil/Pandas-Bokeh#33] opened 2019-07-22 11:47 UTC
Running the following code inside jupyterlab 1.0.2 causes an error

```
import pandas as pd
import pandas_bokeh
pandas_bokeh.output_notebook()

raw_data = {
    'age': [42, 52, 36, 24, 73], 
    'score': [25, 94, 57, 62, 70]
}
df = pd.DataFrame(raw_data, columns = ['age', 'score', ])

df.plot_bokeh(x='age', y='score', title='Age vs Score')
df.plot_bokeh(x='age', y='score', title='Age vs Score', figsize=(9, 5))
```

First plot works but second plot causes

```Javascript Error: invalid bbox {left: 45, top: 29, right: -21, bottom: -40}```

**Comment by PatrikHlobil** [comment] 2019-07-22 13:23
Hi @timhughes ,

it also doesn't work in Jupyter Notebooks. The problem is that your figsize is too small. In matplotlib, this is valid (see https://stackoverflow.com/questions/13714454/specifying-and-saving-a-figure-with-exact-size-in-pixels), but in Bokeh the figsize is defined in pixels. Thus, a 9x5 pixel plot doesn't work, because there is no place for the axes, etc. 

Just try for example (900, 500), then you get a 900x500 pixel image. 

Please answer if this solves your problem such that I can close the issue.

Best,

Patrik

**Comment by timhughes** [comment] 2019-07-23 09:40
Works perfectly, I had completely forgotten that Bokeh has sensible sizes. - sorry

**Comment by PatrikHlobil** [comment] 2019-07-23 16:08
Great to hear 😉. 

Best Patrik

**Closed by PatrikHlobil** 2019-07-23 16:08 UTC
